const card = [
  {
    type: "2",
    qize: "2×1",
    answer: "2",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×2",
    answer: "4",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×3",
    answer: "6",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×4",
    answer: "8",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×5",
    answer: "10",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×6",
    answer: "12",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×7",
    answer: "14",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×8",
    answer: "16",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "2",
    qize: "2×9",
    answer: "18",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×1",
    answer: "3",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×2",
    answer: "6",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×3",
    answer: "9",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×4",
    answer: "12",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×5",
    answer: "15",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×6",
    answer: "18",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×7",
    answer: "21",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×8",
    answer: "24",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "3",
    qize: "3×9",
    answer: "27",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×1",
    answer: "4",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×2",
    answer: "8",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×3",
    answer: "12",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×4",
    answer: "16",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×5",
    answer: "20",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×6",
    answer: "24",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×7",
    answer: "28",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×8",
    answer: "32",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "4",
    qize: "4×9",
    answer: "36",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×1",
    answer: "5",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×2",
    answer: "10",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×3",
    answer: "15",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×4",
    answer: "20",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×5",
    answer: "25",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×6",
    answer: "30",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×7",
    answer: "35",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×8",
    answer: "40",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "5",
    qize: "5×9",
    answer: "45",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×1",
    answer: "6",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×2",
    answer: "12",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×3",
    answer: "18",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×4",
    answer: "24",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×5",
    answer: "30",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×6",
    answer: "36",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×7",
    answer: "42",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×8",
    answer: "48",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "6",
    qize: "6×9",
    answer: "54",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×1",
    answer: "7",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×2",
    answer: "14",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×3",
    answer: "21",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×4",
    answer: "28",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×5",
    answer: "35",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×6",
    answer: "42",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×7",
    answer: "49",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×8",
    answer: "56",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "7",
    qize: "7×9",
    answer: "63",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×1",
    answer: "8",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×2",
    answer: "16",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×3",
    answer: "24",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×4",
    answer: "32",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×5",
    answer: "40",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×6",
    answer: "48",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×7",
    answer: "56",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×8",
    answer: "64",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "8",
    qize: "8×9",
    answer: "72",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×1",
    answer: "9",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×2",
    answer: "18",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×3",
    answer: "27",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×4",
    answer: "36",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×5",
    answer: "45",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×6",
    answer: "54",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×7",
    answer: "63",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×8",
    answer: "72",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
  {
    type: "9",
    qize: "9×9",
    answer: "81",
    qback: true,
    aback: true,
    qclear: false,
    aclear: false,
  },
];
